version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URL=${MONGO_URL}
    working_dir: /app
    stdin_open: true
    tty: true
    network_mode: "host"
