version: '3.8'

services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGO_URL=mongodb://host.docker.internal:27017/unchained_core
      - MONGODB_URL=mongodb://host.docker.internal:27017/unchained_core
      - UNCHAINED_ENDPOINT=http://localhost:3001/graphql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge